let x = 20;
console.log("X = ", x, "Type of : ", typeof(x))
x = "Sunflower"
console.log("X = ", x, "Type of : ", typeof(x))
x = true
console.log("X = ", x, "Type of : ",typeof(x))
x = 20.233;
console.log("X = ", x, "Type of : ",typeof(x))
y=[100,1000,"Chitra"]
console.log("Y = ", y, "Type of : ",typeof(y))
z=new String("India")
console.log("Y = ", z, "Type of : ",typeof(z))
x=`This is a flower and you are a Fool !`
console.log("X = ", x, "Type of : ",typeof(x))